create table Person(id int primary key generated by default as identity,
 username varchar(100), photo varchar, email varchar(200), password varchar, decency int, role varchar, partyquantity int);

create table Party(id int primary key generated by default as identity, type varchar(100), age_restriction int, address varchar(200), date varchar,
name varchar, organizer_id int references Person(id));
create table party_guests ( person_id INT,
                            party_id INT,
                            FOREIGN KEY (person_id) REFERENCES Person (id),
                            FOREIGN KEY (party_id) REFERENCES Party (id));

create table organizer(id int primary key generated by default as identity,
                       username varchar(100), photo varchar, email varchar(200), password varchar, tg varchar, kol_party int);